package data.api

import retrofit2.Retrofit
import retrofit2.adapter.rxjava2.RxJava2CallAdapterFactory

/**
 * Holds the api implementation generated by Retrofit. Should be injected things like network client
 * and retrofit builders.
 */
internal object ApiHolder {
    private val retrofit = Retrofit.Builder()
            .baseUrl("https://my.api.url")
            .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
            .validateEagerly(true)
            .build()
    internal val apiImpl = retrofit.create(Api::class.java)
}
